### ISSUE TITLE
$LOG and $STATUSLOG path not right

### ISSUE THREAD

**Issue by shengminjie** [michaelcoburn/mysql-backup-verifier#1]
ROOTDIR="/data/percona"
should be put
'if [ "$MODE" = "test" ] ; then'
before;

if not change,
$STATUSLOG will be made in '/status_2021-03-17.log';

**Comment by michaelcoburn** [comment]
Thank you @shengminjie !! you're right that was some bad syntax. I've fixed it in https://github.com/michaelcoburn/mysql-backup-verifier/commit/38112ad3b550cd9c4e6af88a805d661d16334387
let me know if you continue to see issues.
